export { default as About } from './About/About'
export { default as Accessories } from './Accessories/Accessories'
export { default as Login } from './Auth/Login'
export { default as Register } from './Auth/Register'
export { default as BestSelling } from './BestSelling/BestSelling'
export { default as Home } from './Home/Home'
export { default as TravelKits } from './TravelKits/TravelKits'
export { default as Product } from './Product/Product'
export { default as FrontPage} from './FrontPage/FrontPage'
export { default as Contact } from './Contact/Contact'